// 添加控制器
        app.controller('fans',function($scope){
            $scope.fansarr=[
                {'head':'images/a1.jpg','name':'A','job':'一些工作，一些工作','star':39},
                {'head':'images/a2.jpg','name':'B','job':'一些工作，一些工作','star':66},
                {'head':'images/a3.jpg','name':'C','job':'一些工作，一些工作','star':67},
                {'head':'images/a4.jpg','name':'D','job':'一些工作，一些工作','star':47}
                ];
        })
        app.controller('nav',function($scope){
            $scope.navarr=[
                {'title':'首页','icon':'glyphicon-home','childnav':''},
                {'title':'简介','icon':'glyphicon-file','childnav':''},
                {'title':'信息','icon':'glyphicon-envelope','childnav':''},
                {'title':'操作','icon':'glyphicon-cog','childnav':['设置栏目','更多设置','分割线']}
                ];
        })
        app.controller('m_nav',function($scope){
            $scope.m_navarr=[
                {'m_title':'最新动态','m_link':'/'},
                {'m_title':'简介','m_link':'/introduction'},
                {'m_title':'消息','m_link':'/message'}
            ];
        })
        app.controller('commentController',function($scope){
            $scope.comment={text:''};
        })
        app.controller('ccController',function($scope){
            $scope.comment=[
                {'author':'','time':'','text':'','reply':''},
            ];
        })